image:
    file: .gitpod.Dockerfile
tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp
    - vscode-sqlite

ports:
    - name: Frontend Application
      port: 7236
      protocol: https
